### ISSUE TITLE
optimal step size and other MC parameters

### ISSUE THREAD

**Issue by guruprem** [yueli-compbio/RiVIERA-beta#1]
Hello;

First thanks a lot and congrats on this wonderful tool,
I am currently trying it in our datasets; and encounterd the following issue. Sorry I am not a maths person and please pardon my naivity. 
The tool works fine when I provide a smaller matrix (data). For instance. Using an annotation matrix with the dimension (1774, 100); and with the following MC parameters as mentioned in the example,

    Stepsize= 100
    nsteps = 1000
    max iterations = 1000 

It performs the random sampling fine and provides the ensemble fit (with 430 ensembl sampled size)

However,if I provide a much larger matrix (say 1774:300) and with the same parameters, it is not able to sample anything. I tried to increase the number of iterations. From a bit reading, it is important to set the leapfrog parameters correct and more importantly smaller for an accurate estimates. Currently the leapfrog size is (0.1).

So my question is,

    1. is there a correlation between the step size parameters and the size of the matrix
    2. if there is a correlation, how can I estimate an optimal setting, given the size of my matrix.

I am so sorry if i do not make sense, as I mentioned I am a novice to this field. Thanks in advance.

M

P.S

The final annotation matrix will be having (594) epigenomes, and currently I am looking at locus wise - so the 1774 SNPs comes from the same locus. I define the locus based on plus or minus 500 kb from the top SNP.

**Comment by yueli-compbio** [comment]
Thank you for your interest. The stepsize should not be greater than 1. I usually find setting stepsize to 0.01 or smaller works well for large number of annotations. As a rule of thumb, a good stepsize should give ~60% HMC acceptance rate as output during the training. There are more sophisticated algorithm (e.g. no U-turn sampler by Hoffman and Gelman, 2014) that automatically adjust the step number and stepsize on the fly. However, I have not got chance to implement that. The current implementation follows the standard HMC introduced by Radford Neal much earlier. Any further question please me know.

**Comment by guruprem** [comment]
Thanks for your input, this is getting bit clearer now. I was referring to this paper **"How the maximum step size in Monte Carlo simulations should be adjusted"** by Robert H. Swendsen. To get to know about the step size and its importance. It is a very interesting field, i have to say. 
_**The other question I had in mind is on the weighted annotation (ev).**_ 
This was mentioned as one of the outputs in the model figure (in the paper) and as well in the vignette. I know this is calculated intrinsicly by the R package with the provided annotation matrix. Is there a way or function to output the weighted epigenomic annotation. Looking forward to your input.

**Comment by yueli-compbio** [comment]
There is an enrichment function called "enrichTest" in the package you can use. Weighting annotations simply multiplies annotations with the global enrichment estimates that one can easily do outside the function call.
