### ISSUE TITLE
MCMC matrix error

### ISSUE THREAD

**Issue by casalex** [yueli-compbio/RiVIERA-beta#5]
When running the rivieraBeta function I get the following error.

**error: Mat::operator(): indices out of bounds or incorrectly used**

It appears to get to iteration 30 before throwing the error. These are the settings I used:

Settings: 
max_epoch = 1000
mu0 = 0.1; phi0 = 2
causalfrac =0.01; useAnn =1
step = 0.001; nsteps = 100
printfreq = 10; verbose = 1

I was wondering how best to figure out what is causing the issue--I am not familiar with debugging the underlying libraries.

**Comment by yueli-compbio** [comment]
What are the input data? My hunch is some inconsistency in annotation, snp, ld matrices in terms of the SNP ordering.

**Comment by casalex** [comment]
The input is 9,075,843 snps (sorted, no chromosome X) and 183 annotations (also sorted and without chrX) from encode. I also checked the the causal snp locations and they should be in order as well. I've included the output from running str() on the main inputs along with the output from the test data of the package for comparison.

**_> str(gwasPval) # p-values_**
_#test data_
 num [1:2596, 1] 0.423 0.366 0.111 0.567 0.308 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:2596] "rs115628345" "rs185665406" "rs185725797" "rs77753606" ...
  ..$ : NULL

_#my data_
num [1:9075843, 1] 0.208 0.33 0.305 0.513 0.843 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:9075843] "rs1" "rs2" "rs3" "rs4" ...
  ..$ : chr "gwasPval_init....1."

**_> str(simdata$ann) # annotation matrix_**
_#test data_
 num [1:2596, 1:100] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:2596] "rs115628345" "rs185665406" "rs185725797" "rs77753606" ...
  ..$ : chr [1:100] "E007-DNase.pval.signal.bigwig.RData" "E007-H3K27me3.pval.signal.bigwig.RData" "E007-H3K4me1.pval.signal.bigwig.RData" "E007-H3K4me3.pval.signal.bigwig.RData" ...

_#my data_
 num [1:9075843, 1:183] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:9075843] "rs1" "rs2" "rs3" "rs4" ...
  ..$ : chr [1:183] "ENCFF692EWL" "ENCFF507VHP" "ENCFF427RYJ" "ENCFF047SHC" ...

**_> str(simdata$blocksize) # block sizes_**
_#test data_
 num [1:15] 162 206 230 181 145 156 199 144 146 226 ...

_#my data_
 num [1:105] 30 227 24 98 224 766 243 53 111 499 ...

**_> str(simdata$causal_snpid) # id numbers for causal snps_**
_#test data_
 chr [1:15] "rs73085230" "rs2292849" "rs62328407" "rs17409755" ...

_#my data_
 chr [1:105] "rs100" "rs101" "rs102" "rs103" ...

**Comment by yueli-compbio** [comment]
You need to specify loci by providing a matrix with two columns indicating the start and end indices of the SNPs (columns) for each locus (rows). Also. I think it's not efficient to run on the full genome wide SNPs.

On Jul 9, 2017, at 11:01 PM, casalex <notifications@github.com<mailto:notifications@github.com>> wrote:


The input is 9,075,843 snps (sorted, no chromosome X) and 183 annotations (also sorted and without chrX) from encode. I also checked the the causal snp locations and they should be in order as well. I've included the output from running str() on the main inputs.

> str(gwasPval) # p-values
#test data
num [1:2596, 1] 0.423 0.366 0.111 0.567 0.308 ...

  *   attr(*, "dimnames")=List of 2
..$ : chr [1:2596] "rs115628345" "rs185665406" "rs185725797" "rs77753606" ...
..$ : NULL

#my data
num [1:9075843, 1] 0.208 0.33 0.305 0.513 0.843 ...

  *   attr(*, "dimnames")=List of 2
..$ : chr [1:9075843] "rs1" "rs2" "rs3" "rs4" ...
..$ : chr "gwasPval_init....1."

> str(simdata$ann) # annotation matrix
#test data
num [1:2596, 1:100] 0 0 0 0 0 0 0 0 0 0 ...

  *   attr(*, "dimnames")=List of 2
..$ : chr [1:2596] "rs115628345" "rs185665406" "rs185725797" "rs77753606" ...
..$ : chr [1:100] "E007-DNase.pval.signal.bigwig.RData" "E007-H3K27me3.pval.signal.bigwig.RData" "E007-H3K4me1.pval.signal.bigwig.RData" "E007-H3K4me3.pval.signal.bigwig.RData" ...

#my data
num [1:9075843, 1:183] 0 0 0 0 0 0 0 0 0 0 ...

  *   attr(*, "dimnames")=List of 2
..$ : chr [1:9075843] "rs1" "rs2" "rs3" "rs4" ...
..$ : chr [1:183] "ENCFF692EWL" "ENCFF507VHP" "ENCFF427RYJ" "ENCFF047SHC" ...

> str(simdata$blocksize) # block sizes
#test data
num [1:15] 162 206 230 181 145 156 199 144 146 226 ...

#my data
num [1:105] 30 227 24 98 224 766 243 53 111 499 ...

> str(simdata$causal_snpid) # id numbers for causal snps
#test data
chr [1:15] "rs73085230" "rs2292849" "rs62328407" "rs17409755" ...

#my data
chr [1:105] "rs100" "rs101" "rs102" "rs103" ...

**Comment by casalex** [comment]
I should have mentioned that, I apologize. I did run the provided function to generate the locus index (see below)--the error is not due to its absence. I will try splitting it into smaller chunks.

locus_index <- make_locus_index(locus_cnt = blocksize)

**_>str(locus_index)_**
 num [1:105, 1:3] 1 2 3 4 5 6 7 8 9 10 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:3] "locusID" "SNP_start" "SNP_end"

**_>head(locus_index)_**
     locusID SNP_start SNP_end
[1,]       1         0      29
[2,]       2        30     256
[3,]       3       257     280
[4,]       4       281     378
[5,]       5       379     602
[6,]       6       603    1368

**Comment by casalex** [comment]
It was in fact a malformed index. Thank you for your help--closing this.
